// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using egitim.Data;

namespace egitim.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200527065342_add-migration init")]
    partial class addmigrationinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("egitim.Models.admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kul");

                    b.Property<string>("sifre");

                    b.HasKey("id");

                    b.ToTable("admin_table");
                });

            modelBuilder.Entity("egitim.Models.canli", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ders_id");

                    b.Property<int?>("derslerid");

                    b.Property<string>("link");

                    b.Property<string>("tarih")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("derslerid");

                    b.ToTable("canli_table");
                });

            modelBuilder.Entity("egitim.Models.cevaplar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("a");

                    b.Property<string>("b");

                    b.Property<string>("c");

                    b.Property<string>("d");

                    b.Property<string>("e");

                    b.Property<int>("konu_id");

                    b.Property<int>("ogrenci_id");

                    b.Property<string>("sonuc");

                    b.Property<int>("soru_sira");

                    b.Property<int>("test_id");

                    b.HasKey("id");

                    b.ToTable("cevaplar_table");
                });

            modelBuilder.Entity("egitim.Models.dersler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ders");

                    b.HasKey("id");

                    b.ToTable("dersler_table");
                });

            modelBuilder.Entity("egitim.Models.konular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ders_id");

                    b.Property<int?>("derslerid");

                    b.Property<string>("dokuman");

                    b.Property<string>("konu");

                    b.Property<int>("sinav");

                    b.Property<int>("sira");

                    b.Property<string>("video");

                    b.Property<string>("youtube");

                    b.HasKey("id");

                    b.HasIndex("derslerid");

                    b.ToTable("konular_table");
                });

            modelBuilder.Entity("egitim.Models.odev", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ders_id");

                    b.Property<int?>("derslerid");

                    b.Property<int>("konu_id");

                    b.Property<string>("odevs");

                    b.Property<int?>("ogrenciid");

                    b.HasKey("id");

                    b.HasIndex("derslerid");

                    b.HasIndex("ogrenciid");

                    b.ToTable("odev_table");
                });

            modelBuilder.Entity("egitim.Models.ogrenci", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad");

                    b.Property<string>("burs");

                    b.Property<int>("ders_id");

                    b.Property<string>("dtarih");

                    b.Property<string>("egitim");

                    b.Property<string>("kayit");

                    b.Property<string>("kul");

                    b.Property<string>("onay");

                    b.Property<string>("sifre");

                    b.Property<string>("soyad");

                    b.Property<string>("sube");

                    b.Property<string>("tcno");

                    b.Property<string>("telefon");

                    b.HasKey("id");

                    b.ToTable("ogrenci_table");
                });

            modelBuilder.Entity("egitim.Models.sinav", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("a");

                    b.Property<string>("b");

                    b.Property<string>("c");

                    b.Property<string>("cevap");

                    b.Property<string>("d");

                    b.Property<int>("ders_id");

                    b.Property<int?>("derslerid");

                    b.Property<string>("e");

                    b.Property<int>("konu_id");

                    b.Property<int?>("konularid");

                    b.Property<int?>("ogrenciid");

                    b.Property<string>("soru");

                    b.Property<int>("soru_sira");

                    b.Property<int>("test_id");

                    b.HasKey("id");

                    b.HasIndex("derslerid");

                    b.HasIndex("konularid");

                    b.HasIndex("ogrenciid");

                    b.ToTable("sinav_table");
                });

            modelBuilder.Entity("egitim.Models.canli", b =>
                {
                    b.HasOne("egitim.Models.dersler", "dersler")
                        .WithMany("canli")
                        .HasForeignKey("derslerid");
                });

            modelBuilder.Entity("egitim.Models.konular", b =>
                {
                    b.HasOne("egitim.Models.dersler", "dersler")
                        .WithMany("konulars")
                        .HasForeignKey("derslerid");
                });

            modelBuilder.Entity("egitim.Models.odev", b =>
                {
                    b.HasOne("egitim.Models.dersler", "dersler")
                        .WithMany("odevs")
                        .HasForeignKey("derslerid");

                    b.HasOne("egitim.Models.ogrenci")
                        .WithMany("odevs")
                        .HasForeignKey("ogrenciid");
                });

            modelBuilder.Entity("egitim.Models.sinav", b =>
                {
                    b.HasOne("egitim.Models.dersler")
                        .WithMany("sinavs")
                        .HasForeignKey("derslerid");

                    b.HasOne("egitim.Models.konular", "konular")
                        .WithMany()
                        .HasForeignKey("konularid");

                    b.HasOne("egitim.Models.ogrenci", "ogrenci")
                        .WithMany("sinavs")
                        .HasForeignKey("ogrenciid");
                });
#pragma warning restore 612, 618
        }
    }
}
